package org.nectarframework.www.data;

import org.nectarframework.base.service.ServiceRegister;
import org.nectarframework.base.service.datastore.DataStoreObject;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptor;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorColumn;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorKey;
import org.nectarframework.base.service.datastore.DataStoreService;

// THIS CLASS IS AUTO GENERATED by nectar.base.service.datastore.dsobuilder.DataStoreObjectBuilder, and configured by config/dataStoreObjects.xml . 
// Edits to this file will be overwritten!
public class Article extends DataStoreObject {
	
	public Article() {
	}
	
	@Override
	public void initDataStoreObjectDescriptor(DataStoreService dss) {
		dss.initDataStoreObjectDescriptor(new DataStoreObjectDescriptor("org_nectarframework_www_article", new DataStoreObjectDescriptorKey(new DataStoreObjectDescriptorColumn("id", DataStoreObjectDescriptorColumn.Type.INT, false), 4, false), new DataStoreObjectDescriptorColumn[] {new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.INT,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.INT,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.INT,false)}, Article.class));
	}
	
	public static Article load(Integer key) throws Exception {
		DataStoreService dss = (DataStoreService) ServiceRegister.getService(DataStoreService.class);
		DataStoreObject dso = dss.loadDSO(dss.getDataStoreObjectDescriptor(Article.class), key);
		if (dso == null) 
			return null;
		return (Article)dso;
	}
	
	public Integer getId() {
		return getInteger("id");
	}
	
	public void setId(Integer id) {
		set("id", id);
	}
	
	public String getName() {
		return getString("name");
	}
	
	public void setName(String name) {
		set("name", name);
	}
	
	public String getContent() {
		return getString("content");
	}
	
	public void setContent(String content) {
		set("content", content);
	}
	
}
