package org.nectarframework.www.data;

import org.nectarframework.base.service.ServiceRegister;
import org.nectarframework.base.service.datastore.DataStoreObject;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptor;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorColumn;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorKey;
import org.nectarframework.base.service.datastore.DataStoreService;

// THIS CLASS IS AUTO GENERATED by nectar.base.service.datastore.dsobuilder.DataStoreObjectBuilder, and configured by config/dataStoreObjects.xml . 
// Edits to this file will be overwritten!
public class BlogPost extends DataStoreObject {
	
	public BlogPost() {
	}
	
	@Override
	public void initDataStoreObjectDescriptor(DataStoreService dss) {
		dss.initDataStoreObjectDescriptor(new DataStoreObjectDescriptor("org_nectarframework_www_blog_post", new DataStoreObjectDescriptorKey(new DataStoreObjectDescriptorColumn("id", DataStoreObjectDescriptorColumn.Type.LONG, false), 8, true), new DataStoreObjectDescriptorColumn[] {new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("true", DataStoreObjectDescriptorColumn.Type.LONG,true), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("true", DataStoreObjectDescriptorColumn.Type.LONG,true)}, BlogPost.class));
	}
	
	public static BlogPost load(Long key) throws Exception {
		DataStoreService dss = (DataStoreService) ServiceRegister.getService(DataStoreService.class);
		DataStoreObject dso = dss.loadDSO(dss.getDataStoreObjectDescriptor(BlogPost.class), key);
		if (dso == null) 
			return null;
		return (BlogPost)dso;
	}
	
	public Long getId() {
		return getLong("id");
	}
	
	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getAuthorUserId() {
		return getLong("authorUserId");
	}
	
	public void setAuthorUserId(Long authorUserId) {
		set("authorUserId", authorUserId);
	}
	
	public Long getCreatedTimestamp() {
		return getLong("createdTimestamp");
	}
	
	public void setCreatedTimestamp(Long createdTimestamp) {
		set("createdTimestamp", createdTimestamp);
	}
	
	public Long getLastEditTimestamp() {
		return getLong("lastEditTimestamp");
	}
	
	public void setLastEditTimestamp(Long lastEditTimestamp) {
		set("lastEditTimestamp", lastEditTimestamp);
	}
	
	public String getTitle() {
		return getString("title");
	}
	
	public void setTitle(String title) {
		set("title", title);
	}
	
	public String getMessage() {
		return getString("message");
	}
	
	public void setMessage(String message) {
		set("message", message);
	}
	
	public String getTags() {
		return getString("tags");
	}
	
	public void setTags(String tags) {
		set("tags", tags);
	}
	
	public org.nectarframework.www.data.User getAuthor() throws Exception {
		return org.nectarframework.www.data.User.load(getLong("authorUserId"));
	}
	
}
