package org.nectarframework.www.data;

import org.nectarframework.base.service.ServiceRegister;
import org.nectarframework.base.service.datastore.DataStoreObject;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptor;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorColumn;
import org.nectarframework.base.service.datastore.DataStoreObjectDescriptorKey;
import org.nectarframework.base.service.datastore.DataStoreService;

// THIS CLASS IS AUTO GENERATED by nectar.base.service.datastore.dsobuilder.DataStoreObjectBuilder, and configured by config/dataStoreObjects.xml . 
// Edits to this file will be overwritten!
public class Structure extends DataStoreObject {
	
	public Structure() {
	}
	
	@Override
	public void initDataStoreObjectDescriptor(DataStoreService dss) {
		dss.initDataStoreObjectDescriptor(new DataStoreObjectDescriptor("org_nectarframework_www_structure", new DataStoreObjectDescriptorKey(new DataStoreObjectDescriptorColumn("structureId", DataStoreObjectDescriptorColumn.Type.LONG, false), 8, false), new DataStoreObjectDescriptorColumn[] {new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("false", DataStoreObjectDescriptorColumn.Type.LONG,false), new DataStoreObjectDescriptorColumn("true", DataStoreObjectDescriptorColumn.Type.LONG,true)}, Structure.class));
	}
	
	public static Structure load(Long key) throws Exception {
		DataStoreService dss = (DataStoreService) ServiceRegister.getService(DataStoreService.class);
		DataStoreObject dso = dss.loadDSO(dss.getDataStoreObjectDescriptor(Structure.class), key);
		if (dso == null) 
			return null;
		return (Structure)dso;
	}
	
	public Long getStructureId() {
		return getLong("structureId");
	}
	
	public void setStructureId(Long structureId) {
		set("structureId", structureId);
	}
	
	public Long getParentId() {
		return getLong("parentId");
	}
	
	public void setParentId(Long parentId) {
		set("parentId", parentId);
	}
	
	public Float getOrderWeight() {
		return getFloat("orderWeight");
	}
	
	public void setOrderWeight(Float orderWeight) {
		set("orderWeight", orderWeight);
	}
	
	public String getName() {
		return getString("name");
	}
	
	public void setName(String name) {
		set("name", name);
	}
	
	public String getDescription() {
		return getString("description");
	}
	
	public void setDescription(String description) {
		set("description", description);
	}
	
	public org.nectarframework.www.data.Structure getParent() throws Exception {
		return org.nectarframework.www.data.Structure.load(getLong("parentId"));
	}
	
}
